name: Southgate Splash

url: https://southgate-splash.github.io/

ghe: https://github.com/Southgate-Splash

highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    toc_levels: 1..3

gems:
  - jekyll-sitemap
